#!$PREFIX/bin/bash

pkg update -y && pkg upgrade -y

if [ ! -r /sdcard/htdocs ]
then
termux-setup-storage
sleep 5
fi

pkg install apache2 php php-apache phpmyadmin mariadb nodejs cloudflared -y
npm install -g pm2

htdocs='/sdcard/htdocs'
index='/sdcard/htdocs/index.php'
php='/data/data/com.termux/files/usr/etc/php'
phpini='/data/data/com.termux/files/usr/etc/php/php.ini'
if [ ! -d $htdocs ];
then
  mkdir $htdocs
fi
if [ ! -d $php ];
then
  mkdir $php
fi
if [ ! -d $phpini ];
then
  cp termux-web-server/php.ini $phpini
fi
if [ ! -d $index ];
then
  cp termux-web-server/index.php $index
fi

rm $PREFIX/etc/apache2/httpd.conf

cp termux-web-server/httpd.conf $PREFIX/etc/apache2/

SECRET=$(tr -dc 'a-z0-9' </dev/urandom | head -c 32)

sed -i "s|^\$cfg\['blowfish_secret'\].*|\$cfg['blowfish_secret'] = '$SECRET';|" \
/data/data/com.termux/files/usr/share/phpmyadmin/config.inc.php

echo blowfish_secret: "$SECRET"

grep -q "^\$cfg\['Servers'\].*\['socket'\]" /data/data/com.termux/files/usr/share/phpmyadmin/config.inc.php || \
sed -i "/\['host'\] = 'localhost';/a\\\$cfg['Servers'][\$i]['socket'] = '/data/data/com.termux/files/usr/var/run/mysqld.sock';" \
/data/data/com.termux/files/usr/share/phpmyadmin/config.inc.php

rm $PREFIX/bin/starjet

cp termux-web-server/starjet $PREFIX/bin/

chmod +x $PREFIX/bin/starjet

echo "Web server installed sucussfully..."
echo "/sdcard/htdocs - is your document directory.."
echo "Place your files in /sdcard/htdocs"
echo "Starting web server"
echo "Starting web server next time"
echo "use command \"starjet\""

starjet start

echo "Running Web Server"

termux-open-url http://localhost:8080/
